import { Role } from '../types';

export interface RolePermissions {
  allowedRoutes: string[];
  canCreateRisk: boolean;
  canCreateAction: boolean;
  canCreateTask: boolean;
  canUploadDocument: boolean;
  canManageUsers: boolean;
  isReadOnly: boolean;
  roleDescription: string;
}

export const ROLE_PERMISSIONS_MAP: Record<Role, RolePermissions> = {
  Administrator: {
    allowedRoutes: [
      '/',
      '/strategy',
      '/performance',
      '/enterprise-risk',
      '/cyber-risk',
      '/governance',
      '/compliance',
      '/bcm',
      '/actions',
      '/tasks',
      '/documents',
      '/reports',
      '/admin',
    ],
    canCreateRisk: true,
    canCreateAction: true,
    canCreateTask: true,
    canUploadDocument: true,
    canManageUsers: true,
    isReadOnly: false,
    roleDescription: 'Full system administration, security, user RBAC and data control.',
  },
  'Strategy Manager': {
    allowedRoutes: [
      '/',
      '/strategy',
      '/performance',
      '/actions',
      '/tasks',
      '/documents',
      '/reports',
    ],
    canCreateRisk: false,
    canCreateAction: true,
    canCreateTask: true,
    canUploadDocument: true,
    canManageUsers: false,
    isReadOnly: false,
    roleDescription: 'Strategy architecture, OKR performance, initiatives and action tracking.',
  },
  'Risk Manager': {
    allowedRoutes: [
      '/',
      '/enterprise-risk',
      '/cyber-risk',
      '/performance',
      '/actions',
      '/tasks',
      '/documents',
      '/reports',
    ],
    canCreateRisk: true,
    canCreateAction: true,
    canCreateTask: true,
    canUploadDocument: true,
    canManageUsers: false,
    isReadOnly: false,
    roleDescription: 'Enterprise risk register (ISO 31000), 5×5 heatmap and risk treatment.',
  },
  'Compliance Manager': {
    allowedRoutes: [
      '/',
      '/governance',
      '/compliance',
      '/cyber-risk',
      '/documents',
      '/reports',
    ],
    canCreateRisk: false,
    canCreateAction: true,
    canCreateTask: false,
    canUploadDocument: true,
    canManageUsers: false,
    isReadOnly: false,
    roleDescription: 'NCA ECC & ISO framework compliance, policies and audit findings.',
  },
  'BCM Manager': {
    allowedRoutes: [
      '/',
      '/bcm',
      '/enterprise-risk',
      '/tasks',
      '/documents',
      '/reports',
    ],
    canCreateRisk: false,
    canCreateAction: true,
    canCreateTask: true,
    canUploadDocument: true,
    canManageUsers: false,
    isReadOnly: false,
    roleDescription: 'Business continuity (ISO 22301), BIA recovery and drill exercises.',
  },
  Executive: {
    allowedRoutes: [
      '/',
      '/strategy',
      '/performance',
      '/enterprise-risk',
      '/cyber-risk',
      '/governance',
      '/compliance',
      '/bcm',
      '/reports',
    ],
    canCreateRisk: false,
    canCreateAction: false,
    canCreateTask: false,
    canUploadDocument: false,
    canManageUsers: false,
    isReadOnly: true,
    roleDescription: 'Executive command center view-only oversight across all organizational domains.',
  },
  Auditor: {
    allowedRoutes: [
      '/',
      '/enterprise-risk',
      '/cyber-risk',
      '/governance',
      '/compliance',
      '/documents',
      '/reports',
    ],
    canCreateRisk: false,
    canCreateAction: false,
    canCreateTask: false,
    canUploadDocument: false,
    canManageUsers: false,
    isReadOnly: true,
    roleDescription: 'Independent audit view of compliance evidence, risk logs and policy versions.',
  },
  Viewer: {
    allowedRoutes: [
      '/',
      '/strategy',
      '/performance',
      '/documents',
      '/reports',
    ],
    canCreateRisk: false,
    canCreateAction: false,
    canCreateTask: false,
    canUploadDocument: false,
    canManageUsers: false,
    isReadOnly: true,
    roleDescription: 'Standard read-only stakeholder view for strategic reports and documents.',
  },
};
