import { Role } from '../types';

export interface RolePermissions {
  allowedRoutes: string[];
  canCreateRisk: boolean;
  canCreateAction: boolean;
  canCreateTask: boolean;
  canCreateStrategy: boolean;
  canUploadDocument: boolean;
  canManageUsers: boolean;
  isReadOnly: boolean;
  roleDescription: string;
}

export const ROLE_PERMISSIONS_MAP: Record<Role, RolePermissions> = {
  Administrator: {
    allowedRoutes: [
      '/',
      '/organization/setup',
      '/strategy',
      '/strategy/create',
      '/hierarchy-tree',
      '/objectives',
      '/kpis',
      '/initiatives',
      '/org-structure',
      '/users',
      '/performance',
      '/enterprise-risk',
      '/cyber-risk',
      '/governance',
      '/compliance',
      '/bcm',
      '/actions',
      '/tasks',
      '/documents',
      '/reports',
      '/admin',
    ],
    canCreateRisk: true,
    canCreateAction: true,
    canCreateTask: true,
    canCreateStrategy: true,
    canUploadDocument: true,
    canManageUsers: true,
    isReadOnly: false,
    roleDescription: 'Full system administration, security, user RBAC and data control (Support Services IT).',
  },
  'Authority Board & CEO': {
    allowedRoutes: [
      '/',
      '/organization/setup',
      '/strategy',
      '/strategy/create',
      '/hierarchy-tree',
      '/objectives',
      '/kpis',
      '/initiatives',
      '/org-structure',
      '/users',
      '/performance',
      '/enterprise-risk',
      '/cyber-risk',
      '/governance',
      '/compliance',
      '/bcm',
      '/reports',
    ],
    canCreateRisk: false,
    canCreateAction: false,
    canCreateTask: false,
    canCreateStrategy: true,
    canUploadDocument: false,
    canManageUsers: false,
    isReadOnly: false,
    roleDescription: 'Strategic command oversight, executive OKRs, risk appetite governance, and board reporting.',
  },
  'Sector Director General': {
    allowedRoutes: [
      '/',
      '/organization/setup',
      '/strategy',
      '/strategy/create',
      '/hierarchy-tree',
      '/objectives',
      '/kpis',
      '/initiatives',
      '/org-structure',
      '/users',
      '/performance',
      '/actions',
      '/tasks',
      '/documents',
      '/reports',
    ],
    canCreateRisk: false,
    canCreateAction: true,
    canCreateTask: true,
    canCreateStrategy: true,
    canUploadDocument: true,
    canManageUsers: false,
    isReadOnly: false,
    roleDescription: 'Operational sector leadership, cascading matrix OKRs, 2026/2027 KPIs, and strategic initiatives.',
  },
  'Department Manager': {
    allowedRoutes: [
      '/',
      '/organization/setup',
      '/org-structure',
      '/users',
      '/performance',
      '/bcm',
      '/actions',
      '/tasks',
      '/documents',
      '/reports',
    ],
    canCreateRisk: false,
    canCreateAction: true,
    canCreateTask: true,
    canCreateStrategy: false,
    canUploadDocument: true,
    canManageUsers: false,
    isReadOnly: false,
    roleDescription: 'Departmental execution, operational task assignments, and action plan mitigation updates.',
  },
  'GRC & Enterprise Risk': {
    allowedRoutes: [
      '/',
      '/organization/setup',
      '/enterprise-risk',
      '/governance',
      '/compliance',
      '/cyber-risk',
      '/users',
      '/performance',
      '/actions',
      '/tasks',
      '/documents',
      '/reports',
    ],
    canCreateRisk: true,
    canCreateAction: true,
    canCreateTask: true,
    canCreateStrategy: false,
    canUploadDocument: true,
    canManageUsers: false,
    isReadOnly: false,
    roleDescription: 'Enterprise risk register (ISO 31000), 5×5 heatmaps, governance committees, and compliance policies.',
  },
  'Cybersecurity Officer': {
    allowedRoutes: [
      '/',
      '/organization/setup',
      '/cyber-risk',
      '/compliance',
      '/enterprise-risk',
      '/users',
      '/actions',
      '/tasks',
      '/documents',
      '/reports',
    ],
    canCreateRisk: true,
    canCreateAction: true,
    canCreateTask: true,
    canCreateStrategy: false,
    canUploadDocument: true,
    canManageUsers: false,
    isReadOnly: false,
    roleDescription: 'NCA ECC framework compliance, cyber asset posture, threat exposure, and IT security controls.',
  },
  'Internal Audit': {
    allowedRoutes: [
      '/',
      '/organization/setup',
      '/strategy',
      '/hierarchy-tree',
      '/objectives',
      '/kpis',
      '/initiatives',
      '/org-structure',
      '/users',
      '/performance',
      '/enterprise-risk',
      '/cyber-risk',
      '/governance',
      '/compliance',
      '/bcm',
      '/documents',
      '/reports',
    ],
    canCreateRisk: false,
    canCreateAction: false,
    canCreateTask: false,
    canCreateStrategy: false,
    canUploadDocument: false,
    canManageUsers: false,
    isReadOnly: true,
    roleDescription: 'Independent audit inspection across all sectors, compliance evidence, risk logs, and policy trails.',
  },
  'Strategy Manager': {
    allowedRoutes: [
      '/',
      '/organization/setup',
      '/strategy',
      '/strategy/create',
      '/hierarchy-tree',
      '/objectives',
      '/kpis',
      '/initiatives',
      '/org-structure',
      '/users',
      '/performance',
      '/actions',
      '/tasks',
      '/documents',
      '/reports',
    ],
    canCreateRisk: false,
    canCreateAction: true,
    canCreateTask: true,
    canCreateStrategy: true,
    canUploadDocument: true,
    canManageUsers: true,
    isReadOnly: false,
    roleDescription: 'Strategy architecture, OKR performance, initiatives and action tracking.',
  },
  'Strategy Specialist': {
    allowedRoutes: [
      '/',
      '/organization/setup',
      '/strategy',
      '/strategy/create',
      '/hierarchy-tree',
      '/objectives',
      '/kpis',
      '/initiatives',
      '/org-structure',
      '/users',
      '/performance',
      '/actions',
      '/tasks',
      '/documents',
      '/reports',
    ],
    canCreateRisk: false,
    canCreateAction: true,
    canCreateTask: true,
    canCreateStrategy: true,
    canUploadDocument: true,
    canManageUsers: true,
    isReadOnly: false,
    roleDescription: 'Institutional Strategy Specialist responsible for strategy creation, cascading pillars, objectives, KPIs, initiatives, and performance monitoring.',
  },
  'Risk Manager': {
    allowedRoutes: [
      '/',
      '/organization/setup',
      '/enterprise-risk',
      '/cyber-risk',
      '/users',
      '/performance',
      '/actions',
      '/tasks',
      '/documents',
      '/reports',
    ],
    canCreateRisk: true,
    canCreateAction: true,
    canCreateTask: true,
    canCreateStrategy: false,
    canUploadDocument: true,
    canManageUsers: false,
    isReadOnly: false,
    roleDescription: 'Enterprise risk register (ISO 31000), 5×5 heatmap and risk treatment.',
  },
  'Compliance Manager': {
    allowedRoutes: [
      '/',
      '/organization/setup',
      '/governance',
      '/compliance',
      '/cyber-risk',
      '/users',
      '/documents',
      '/reports',
    ],
    canCreateRisk: false,
    canCreateAction: true,
    canCreateTask: false,
    canCreateStrategy: false,
    canUploadDocument: true,
    canManageUsers: false,
    isReadOnly: false,
    roleDescription: 'NCA ECC & ISO framework compliance, policies and audit findings.',
  },
  'BCM Manager': {
    allowedRoutes: [
      '/',
      '/organization/setup',
      '/bcm',
      '/enterprise-risk',
      '/users',
      '/tasks',
      '/documents',
      '/reports',
    ],
    canCreateRisk: false,
    canCreateAction: true,
    canCreateTask: true,
    canCreateStrategy: false,
    canUploadDocument: true,
    canManageUsers: false,
    isReadOnly: false,
    roleDescription: 'Business continuity (ISO 22301), BIA recovery and drill exercises.',
  },
  Executive: {
    allowedRoutes: [
      '/',
      '/organization/setup',
      '/strategy',
      '/strategy/create',
      '/hierarchy-tree',
      '/objectives',
      '/kpis',
      '/initiatives',
      '/org-structure',
      '/users',
      '/performance',
      '/enterprise-risk',
      '/cyber-risk',
      '/governance',
      '/compliance',
      '/bcm',
      '/reports',
    ],
    canCreateRisk: false,
    canCreateAction: false,
    canCreateTask: false,
    canCreateStrategy: true,
    canUploadDocument: false,
    canManageUsers: false,
    isReadOnly: false,
    roleDescription: 'Executive command center oversight with strategy formulation capability.',
  },
  Auditor: {
    allowedRoutes: [
      '/',
      '/organization/setup',
      '/enterprise-risk',
      '/cyber-risk',
      '/governance',
      '/compliance',
      '/users',
      '/documents',
      '/reports',
    ],
    canCreateRisk: false,
    canCreateAction: false,
    canCreateTask: false,
    canCreateStrategy: false,
    canUploadDocument: false,
    canManageUsers: false,
    isReadOnly: true,
    roleDescription: 'Independent audit view of compliance evidence, risk logs and policy versions.',
  },
  Viewer: {
    allowedRoutes: [
      '/',
      '/organization/setup',
      '/strategy',
      '/strategy/create',
      '/hierarchy-tree',
      '/objectives',
      '/kpis',
      '/initiatives',
      '/org-structure',
      '/users',
      '/performance',
      '/documents',
      '/reports',
    ],
    canCreateRisk: false,
    canCreateAction: false,
    canCreateTask: false,
    canCreateStrategy: true,
    canUploadDocument: false,
    canManageUsers: false,
    isReadOnly: false,
    roleDescription: 'Standard stakeholder view with strategy formulation simulation capability.',
  },
};
